# Generated by Django 3.2.8 on 2021-10-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
