# Generated by Django 3.2.8 on 2021-10-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211026_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
