# Generated by Django 3.2.8 on 2021-10-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
