# Generated by Django 3.2.8 on 2021-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
